server:
  port: 8080

#spring:
  #data:
    #mongodb:
      #uri: mongodb://localhost:27017/EmployeeDB
spring:
  datasource:
    url:  jdbc:mysql://sql9.freesqldatabase.com/sql9630227
    username: sql9630227
    password: wfVF8Egylk

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



management:
  endpoint:
    health:
      show-details: always
